FROM openjdk:11
COPY jar-docker-1.0-SNAPSHOT-jar-with-dependencies.jar /fasttec/procastinator/
WORKDIR /fasttec/procastinator/
ENTRYPOINT ["java", "-jar", "jar-docker-1.0-SNAPSHOT-jar-with-dependencies.jar" ]
